config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  # Defines the root path route ("/")
  root "home#index"

  resources :verification_requests, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :verification_requests
end

app/models/verification_request.rb
class VerificationRequest < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 250 }

  module STATUS
    SUCCESS = "success"
    FAIL = "fail"
    PENDING = "pending"
  end

  def success?
    status == STATUS::SUCCESS
  end

  def fail?
    status == STATUS::FAIL
  end

  def pending?
    status == STATUS::PENDING
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/verification_requests_controller.rb
class VerificationRequestsController < ApplicationController
  before_action :authenticate_user!, except: [:show] 

  def index
    @verification_requests = current_user.verification_requests
  end

  def new
    @verification_request = VerificationRequest.new
  end

  def show 
    @verification_request = VerificationRequest.find(params[:id])
  end
  
  def create
    @verification_request = VerificationRequest.new(verification_request_params)

    if @verification_request.save
      @verification_request.update(
        certified_url: verification_request_url(@verification_request)
      )
      redirect_to verification_requests_path, notice: "Verification Request created successfully"
    else
      render :new
    end
  end

  private
  
  def verification_request_params
    params.require(:verification_request).permit(:title, :content).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def button_link(text, url, color: "blue", icon: nil)
    render partial: 'shared/button', locals: { 
      text: text, 
      url: url, 
      icon: icon, 
      classes: "text-white bg-green-700 hover:bg-green-600 focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center" 
    }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/verification_requests_helper.rb
module VerificationRequestsHelper
end

app/views/home/index.html.erb
<p>Landing Page</p>
<p>Human Generated</p>
<p>Explain the mission</p>


<% if current_user %>
  <p>Hello, <%=current_user.email%></p>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <%= link_to "Verification Requests", verification_requests_path %>
<% else %>
  <%= link_to "Get Started", new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HumanGenerated</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-50">
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_badge.html.erb
<div class="inline px-3 py-1 text-sm font-normal rounded-full text-<%= color %>-500 gap-x-2 bg-<%= color %>-100/60">
  <%= text %>
</div>

app/views/shared/_button.html.erb
<%= link_to url, class: classes do %>
  <% unless icon.nil? %>
    <i class="fa-solid fa-<%= icon %>"></i>
  <% end %>
  <%= text %>
<% end %>

app/views/shared/_errors_list_alert.html.erb
<div class="flex p-4 mb-4 text-sm text-red-800 rounded-lg bg-red-50 dark:bg-gray-800 dark:text-red-400" role="alert">
  <svg class="flex-shrink-0 inline w-4 h-4 me-3 mt-[2px]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
    <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
  </svg>
  <span class="sr-only">Danger</span>
  <div>
    <span class="font-medium">Ensure that these requirements are met:</span>
      <ul class="mt-1.5 list-disc list-inside">
        <% errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
    </ul>
  </div>
</div>

app/views/verification_requests/_request_row.html.erb
<tr>
  <td class="px-4 py-4 text-sm font-medium whitespace-nowrap">
    <div>
      <h2 class="font-medium text-gray-800 "><%= verification_request.title %></h2>
    </div>
  </td>
  <td class="px-12 py-4 text-sm font-medium whitespace-nowrap">
    <% badge_color = verification_request.success? ? "emerald" : verification_request.fail? ? "red" : "gray"  %>
    <%= render "shared/badge", text: verification_request.status, color: badge_color %>
  </td>
  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <div>
      <h4 class="text-gray-700"><%= verification_request.created_at %></h4>
    </div>
  </td>

  <td class="px-4 py-4 text-sm whitespace-nowrap">
    <%= link_to verification_request_path(verification_request) do %>
      <i class="fa-regular fa-eye"></i>
    <% end %>
  </td>
</tr>

app/views/verification_requests/_request_table.html.erb
<div class="overflow-hidden border border-gray-200 md:rounded-lg">
  <table class="min-w-full divide-y divide-gray-200">
    <thead class="bg-gray-50">
      <tr>
        <th scope="col" class="py-3.5 px-4 text-sm font-normal text-left rtl:text-right text-gray-500">
          Title
        </th>

        <th scope="col" class="px-12 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500">
          Status
        </th>

        <th scope="col" class="px-4 py-3.5 text-sm font-normal text-left rtl:text-right text-gray-500">
          Submited At
        </th>

        <th scope="col" class="relative py-3.5 px-4">
          <span class="sr-only">Edit</span>
        </th>
      </tr>
    </thead>
    <tbody class="bg-white divide-y divide-gray-200">
      <% @verification_requests.order(created_at: :desc).each do |verification_request| %>
        <%= render "verification_requests/request_row", verification_request: verification_request %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/verification_requests/index.html.erb
<div class="inline-block min-w-full py-2 align-middle md:px-6 lg:px-8">
  <div class="py-4 flex justify-between items-center">
    <%= button_link("New Request", new_verification_request_path, color: "black", icon: "plus") %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "px-2 text-sm" %>
  </div>
  
  <%= render "verification_requests/request_table" %>

  <div class="text-gray-400 p-4 text-center text-xs">
    <div>
      <i class="fa-regular fa-face-smile"></i>
      <i class="fa-solid fa-earth-americas"></i>
    </div>
    <p>Human Generated is a free to use open source project</p>
    <p>Find us on <a href="https://github.com/hmacht/human-generated"><u>GitHub</u></a></p>
  </div>
</div>

app/views/verification_requests/new.html.erb
<div class="max-w-2xl px-4 py-8 mx-auto lg:py-16">
  <% if @verification_request.errors.any? %>
    <%= render "shared/errors_list_alert", errors: @verification_request.errors%>
  <% end %>
  <h2 class="text-xl font-bold text-gray-900 dark:text-white">Create a new request</h2>
  <p class="mb-4 text-md text-gray-600 ">Once a verification request is submitted your certificate and url will be ready in a few minutes (processing time is dependent on request volume).</p>
  <%= form_with model: @verification_request do |f| %>
      <div class="grid gap-4 mb-4 sm:grid-cols-2 sm:gap-6 sm:mb-5">
          <div class="sm:col-span-2">
              <label for="name" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Title*</label>
              <%= f.text_field :title, placeholder: "Content title", class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg bg-white focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %>
              <p class="mt-1 text-sm text-gray-600 ">The title is just for keeping track of your request, and is <u>not</u> part of the verification </p>
          </div>
          <div class="sm:col-span-2">
              <label for="description" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Description*</label>
              <%= f.text_area :content, maxlength: 20000, id: "content_text_area", rows: 8, placeholder: "Any text content that you want to verify as Human Generated...", class: "block p-2.5 w-full text-sm bg-white text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500"  %>
              <span id="char_count">0/20000</span>
          </div>
      </div>
      <div class="flex items-center space-x-4">
          <%= button_tag "Submit", type: "submit", class: "text-white bg-green-700 hover:bg-green-600 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600" %>
          <%= link_to "Cancel", verification_requests_path, class: "border border-gray-300 text-black bg-gray-200 hover:bg-gray-300 focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-5 py-2.5 text-center" %>
      </div>
  <% end %>
</div>
<script>
  // JavaScript code to count characters
  document.addEventListener("DOMContentLoaded", function() {
    var textArea = document.getElementById("content_text_area");
    var charCount = document.getElementById("char_count");
    
    function updateCharCount() {
      var currentLength = textArea.value.length;
      charCount.textContent = currentLength + "/20000";
    }

    textArea.addEventListener("input", updateCharCount);
    updateCharCount();
  });
</script>

app/views/verification_requests/show.html.erb
<% if @verification_request.success? %>
  <div class="fixed top-0 left-0 flex items-center justify-center w-full h-full">
    <div class="relative p-4 w-full max-w-md h-full md:h-auto">
        <ol class="relative border-s border-gray-200 dark:border-gray-700">                  
    <li class="mb-10 ms-6">            
        <%= image_tag "badge.png", class: "-my-1 absolute flex items-center justify-center w-9 h-9 bg-blue-100 rounded-full -start-5" %>
        <h3 class="flex items-center mb-1 text-lg font-semibold text-gray-900 dark:text-white">Human Generated Content <span class="bg-blue-100 text-blue-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300 ms-3">Verified</span></h3>
        <time class="block mb-2 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">Verified on <%= @verification_request.created_at %></time>
        <p class="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">Content titled "<%= @verification_request.title %>" has been verified by humangenerated.com as authentic content written by a human.</p>
        <button onclick="downloadTxt()" type="button" class="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:outline-none focus:ring-gray-100 focus:text-blue-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700 dark:focus:ring-gray-700">
          <i class="fa-solid fa-download"></i> 
          <span>Download proof of content</span>
        </button>
    </li>
    <li class="mb-10 ms-6">
        <span class="-my-1 absolute flex items-center justify-center w-9 h-9 bg-blue-100 rounded-full -start-5">
            <i class="fa-solid fa-code"></i>
        </span>
        <h3 class="mb-1 text-lg font-semibold text-gray-900 dark:text-white">Want to embed a badge on your site?</h3>
        <time class="block mb-2 text-sm font-normal leading-none text-gray-400 dark:text-gray-500"></time>
        <p class="text-base font-normal text-gray-500 dark:text-gray-400">Place this badge next to content that humangenerated.com has verified. A badge must always link it to the verification page for the specified content.</p>
        <div class="w-full max-w-lg">
          <div class="relative bg-gray-100 rounded-lg dark:bg-gray-700 p-4">
            <div class="overflow-scroll max-h-full">
              <pre><code id="code-block" class="text-sm text-gray-500 dark:text-gray-400 whitespace-pre">&lt!-- Human Generated Badge --&gt
&lt;a href="<%= @verification_request.certified_url %>"&gt;
  &lt;img src="path_to_your_image_file" alt="HG Cert."&gt;
&lt;/a&gt;
</code></pre>
            </div>
        </div>
      </div>
    </li>
</ol>
    </div>
</div>
<% else %>

<div class="fixed top-0 left-0 flex items-center justify-center w-full h-full">
    <div class="relative p-4 w-full max-w-md h-full md:h-auto">
        <ol class="relative border-s border-gray-200 dark:border-gray-700">                  
    <li class="mb-10 ms-6">            
        <span class="absolute flex items-center justify-center w-6 h-6 bg-blue-100 rounded-full -start-3 ring-8 ring-white dark:ring-gray-900 dark:bg-blue-900">
            <svg class="w-2.5 h-2.5 text-blue-800 dark:text-blue-300" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
            </svg>
        </span>
        <h3 class="flex items-center mb-1 text-lg font-semibold text-gray-900 dark:text-white">Human Generated Content <span class="bg-blue-100 text-blue-800 text-sm font-medium me-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300 ms-3"><%= @verification_request.status %></span></h3>
        <time class="block mb-2 text-sm font-normal leading-none text-gray-400 dark:text-gray-500">Submitted on <%= @verification_request.created_at %></time>
        <p class="mb-4 text-base font-normal text-gray-500 dark:text-gray-400">Content titled "<%= @verification_request.title %>" has not been verified yet. Please check back later</p>
    </li>
</ol>
    </div>
</div>

<% end %>












<script>
  function downloadTxt() {
    var content = "IMPORTANT: If this file has been shared with you, disregard and don't trust. To get an authentic copy of verified content go to the Certificate URL. \n\nVerification id: <%= @verification_request.id %> \nVerified By: humangenerated.com \nCertificate URL: <%= @verification_request.certified_url %> \n\nVerified Human Generated Content \n------------------------------\n<%= @verification_request.content %>";
    var element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(content));
    element.setAttribute('download', 'hg-content-<%= @verification_request.id %>.txt');
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }
</script>